#!/usr/bin/env bash
# pass update - Password Store Extension (https://www.passwordstore.org/)
# Copyright (C) 2017 Alexandre PUJOL <alexandre@pujol.io>.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# This file should be sourced by all test-scripts
#
# This scripts sets the following:
#   $PASS	Full path to password-store script to test
#   $GPG	Name of gpg executable
#   $KEY{1..5}	GPG key ids of testing keys
#   $TEST_HOME	This folder
#

# shellcheck disable=SC1091

# Project directory
TEST_HOME="$(pwd)"
EXT_HOME="$(dirname "$TEST_HOME")"


# Check dependencies
_die() { echo "${@}" && exit 1; }
PASS="$(which pass)"; GPG="$(which gpg)"; COVERAGE=true; GIT=false
[[ -e "$PASS" ]] || _die "Could not find pass command"
if [[ ! -e "$GPG" ]]; then
	if which gpg2 &>/dev/null; then
		GPG="gpg2"
	else
		_die "Could not find gpg command"
	fi
fi
if [[ $COVERAGE == true ]]; then
	KCOV="$(which kcov)"; [[ -e "$KCOV" ]] || _die "Could not find kcov command"
	_pass() { "$KCOV" --exclude-path="$PASS,$TEST_HOME/fake-editor" "$TMP/$0" "$PASS" "${@}"; }
else
	_pass() { "$PASS" "${@}"; }
fi


# sharness config
source ./sharness
export TMP="/tmp/pass-update"


#  Prepare pass config vars
unset PASSWORD_STORE_DIR
unset PASSWORD_STORE_KEY
unset PASSWORD_STORE_GIT
unset PASSWORD_STORE_GPG_OPTS
unset PASSWORD_STORE_X_SELECTION
unset PASSWORD_STORE_CLIP_TIME
unset PASSWORD_STORE_UMASK
unset PASSWORD_STORE_GENERATED_LENGTH
unset PASSWORD_STORE_CHARACTER_SET
unset PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS
unset PASSWORD_STORE_ENABLE_EXTENSIONS
unset PASSWORD_STORE_EXTENSIONS_DIR
unset PASSWORD_STORE_SIGNING_KEY
unset GNUPGHOME
unset EDITOR

export PASSWORD_STORE_ENABLE_EXTENSIONS=true
export PASSWORD_STORE_EXTENSIONS_DIR="$EXT_HOME"


# GnuPG config
unset GPG_AGENT_INFO
export GNUPGHOME="$TEST_HOME/gnupg/"
export KEY1="D4C78DB7920E1E27F5416B81CC9DB947CF90C77B"
export KEY2="70BD448330ACF0653645B8F2B4DDBFF0D774A374"
export KEY3="62EBE74BE834C2EC71E6414595C4B715EB7D54A8"
export KEY4="9378267629F989A0E96677B7976DD3D6E4691410"
export KEY5="4D2AFBDE67C60F5999D143AFA6E073D439E5020C"
chmod 700 "$GNUPGHOME"


# Test helpers

pass_insert() {
	echo -e "$2\nlogin: zx2c4" | pass insert --multiline --force "$1"
}

test_pass_populate() {
	pass init "$KEY1"
	pass_insert "Business/site.com" "$RANDOM"
	pass_insert "Business/site.eu" "$RANDOM"
	pass_insert "Email/donenfeld.com" "$RANDOM"
	pass_insert "Email/zx2c4.com" "$RANDOM"
	pass_insert "France/bank" "$RANDOM"
	pass_insert "France/freebox" "$RANDOM"
	pass_insert "France/mobilephone" "$RANDOM"
	[[ $GIT == true ]] && pass git init
}

test_cleanup() {
	rm -rf "$TMP"
	mkdir -p "$TMP"
}

test_export() {
	export testname="$1"
	export PASSWORD_STORE_DIR="$TMP/${testname}-store"
	export PASSWORD_STORE_CLIP_TIME="1"
	export PATH="$TEST_HOME:$PATH"
	export EDITOR="fake-editor"
	export GIT_DIR="$PASSWORD_STORE_DIR/.git"
	export GIT_WORK_TREE="$PASSWORD_STORE_DIR"
	git config --global user.email "Pass-Automated-Testing-Suite@zx2c4.com"
	git config --global user.name "Pass Automated Testing Suite"
}

test_xclip() {
	echo "$RANDOM" | xclip -i &> /dev/null
	return $?
}


# Check for auxiliary programs
test_xclip && test_set_prereq XCLIP
